plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'springweb'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// 의존성 (dependencies) { } 안에 추가적인 라이브러리 코드
	// 1. springboot
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// 2. jdbc
	implementation 'org.springframework.boot:spring-boot-starter'
  	runtimeOnly 'com.mysql:mysql-connector-j'

	// 3. 롬복
	compileOnly 'org.projectlombok:lombok'
  	annotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}

// @RequestParam / @PathVariable 등에서 매개변수 이름을 생략해도
// 리플렉션으로 이름을 읽을 수 있도록 -parameters 옵션 추가 (없으면 500 발생)
tasks.withType(JavaCompile).configureEach {
	options.compilerArgs << '-parameters'
}
