INSERT INTO menu (menu_name, menu_price , create_date, update_date) VALUES
                                             ('치즈버거', 5000,now(),now()),
                                             ('불고기버거', 5500,now(),now()),
                                             ('더블불고기버거', 7500,now(),now()),
                                             ('새우버거', 6000,now(),now()),
                                             ('베이컨치즈버거', 7000,now(),now()),
                                             ('클래식버거', 6500,now(),now()),
                                             ('더블치즈버거', 8000,now(),now()),
                                             ('스파이시버거', 7000,now(),now()),
                                             ('치킨버거', 6500,now(),now()),
                                             ('프리미엄버거', 10000,now(),now());
INSERT INTO product (product_name, product_price,create_date, update_date) VALUES
                                                      ('햄버거빵', 500,now(),now()),
                                                      ('소고기패티', 1200,now(),now()),
                                                      ('불고기패티', 1000,now(),now()),
                                                      ('치즈', 300,now(),now()),
                                                      ('양상추', 200,now(),now()),
                                                      ('토마토', 300,now(),now()),
                                                      ('피클', 100,now(),now()),
                                                      ('베이컨', 500,now(),now()),
                                                      ('새우패티', 1300,now(),now()),
                                                      ('치킨패티', 1100,now(),now()),
                                                      ('양파', 150,now(),now()),
                                                      ('스파이시소스', 200,now(),now());
INSERT INTO recipe (menu_no, product_no, recipe_order,create_date, update_date) VALUES
                                                           (1, 1, 1,now(),now()),
                                                           (1, 4, 2,now(),now()),
                                                           (1, 2, 3,now(),now()),
                                                           (1, 5, 4,now(),now()),
                                                           (1, 1, 5,now(),now()),

                                                           (2, 1, 1,now(),now()),
                                                           (2, 3, 2,now(),now()),
                                                           (2, 11, 3,now(),now()),
                                                           (2, 5, 4,now(),now()),
                                                           (2, 1, 5,now(),now()),

                                                           (3, 1, 1,now(),now()),
                                                           (3, 3, 2,now(),now()),
                                                           (3, 4, 3,now(),now()),
                                                           (3, 3, 4,now(),now()),
                                                           (3, 11, 5,now(),now()),
                                                           (3, 5, 6,now(),now()),
                                                           (3, 7, 7,now(),now()),
                                                           (3, 1, 8,now(),now()),

                                                           (4, 1, 1,now(),now()),
                                                           (4, 5, 2,now(),now()),
                                                           (4, 9, 3,now(),now()),
                                                           (4, 7, 4,now(),now()),
                                                           (4, 1, 5,now(),now()),

                                                           (5, 1, 1,now(),now()),
                                                           (5, 8, 2,now(),now()),
                                                           (5, 4, 3,now(),now()),
                                                           (5, 2, 4,now(),now()),
                                                           (5, 6, 5,now(),now()),
                                                           (5, 5, 6,now(),now()),
                                                           (5, 1, 7,now(),now()),

                                                           (6, 1, 1,now(),now()),
                                                           (6, 5, 2,now(),now()),
                                                           (6, 6, 3,now(),now()),
                                                           (6, 7, 4,now(),now()),
                                                           (6, 11, 5,now(),now()),
                                                           (6, 2, 6,now(),now()),
                                                           (6, 1, 7,now(),now()),

                                                           (7, 1, 1,now(),now()),
                                                           (7, 4, 2,now(),now()),
                                                           (7, 2, 3,now(),now()),
                                                           (7, 4, 4,now(),now()),
                                                           (7, 2, 5,now(),now()),
                                                           (7, 5, 6,now(),now()),
                                                           (7, 7, 7,now(),now()),
                                                           (7, 1, 8,now(),now()),

                                                           (8, 1, 1,now(),now()),
                                                           (8, 12, 2,now(),now()),
                                                           (8, 10, 3,now(),now()),
                                                           (8, 11, 4,now(),now()),
                                                           (8, 5, 5,now(),now()),
                                                           (8, 12, 6,now(),now()),
                                                           (8, 1, 7,now(),now()),

                                                           (9, 1, 1,now(),now()),
                                                           (9, 5, 2,now(),now()),
                                                           (9, 10, 3,now(),now()),
                                                           (9, 6, 4,now(),now()),
                                                           (9, 7, 5,now(),now()),
                                                           (9, 1, 6,now(),now()),

                                                           (10, 1, 1,now(),now()),
                                                           (10, 4, 2,now(),now()),
                                                           (10, 2, 3,now(),now()),
                                                           (10, 8, 4,now(),now()),
                                                           (10, 4, 5,now(),now()),
                                                           (10, 2, 6,now(),now()),
                                                           (10, 6, 7,now(),now()),
                                                           (10, 11, 8,now(),now()),
                                                           (10, 5, 9,now(),now()),
                                                           (10, 7, 10,now(),now()),
                                                           (10, 1, 11,now(),now());
INSERT INTO productLog
(productLog_no, product_no, product_qty, product_condition, productLog_price, customerLog_day, create_date, update_date)
VALUES
    (1, 1, 200, '발주', 20000, 1,now(),now()),
    (2, 2, -100, '사용', 0, 1,now(),now()),
    (3, 3, 100, '발주', 30000, 1,now(),now()),
    (4, 5, 150, '발주', 75000, 1,now(),now()),
    (5, 7, 50, '발주', 25000, 2,now(),now()),
    (6, 8, -30, '사용', 0, 2,now(),now()),
    (7, 9, -100, '사용', 0, 2,now(),now()),
    (8, 10, 80, '발주', 12000, 2,now(),now()),
    (9, 4, 40, '사용', 0, 3,now(),now()),
    (10, 6, 120, '발주', 60000, 3,now(),now());